
export const blankCompanySetting = {
  uuid: '',
  company_name: '',
  company_contact: '',
  company_email: '',
  company_phone: '',
  company_address1: '',
  company_address2: '',
  company_city: '',
  company_state: '',
  company_zip_code: '',
  company_country: '',
  company_vat: '',
  company_website: '',
  company_bank_name: '',
  company_bank_account: '',
}
export const validCompanySetting = {
  uuid: 'xyz',
  company_name: 'Company Test',
  company_contact: '',
  company_email: 'test@paper.id',
  company_phone: 290192019,
  company_address1: 'JL. Test company No.01',
  company_address2: '',
  company_city: 'Jakarta Barat',
  company_state: 'DKI Jakarta',
  company_zip_code: '37862',
  company_country: 'Indonesia',
  company_vat: '',
  company_website: '',
  company_bank_name: '',
  company_bank_account: '',
}
export const validCompanySettingAll = {
  uuid: 'xyz',
  company_name: 'Company Test',
  company_contact: 'Inggil',
  company_email: 'test@paper.id',
  company_phone: 290192019,
  company_address1: 'JL. Test company No.01',
  company_address2: 'Kec. Sawangan Bangau',
  company_city: 'Jakarta Barat',
  company_state: 'DKI Jakarta',
  company_zip_code: '37862',
  company_country: 'Indonesia',
  company_vat: 'aw',
  company_website: 'test.id',
  company_bank_name: 'BCA',
  company_bank_account: '03920192910',
}

export const invalidUuid = {
  uuid: '',
  company_name: 'Company Test',
  company_contact: 'Inggil',
  company_email: 'test@paper.id',
  company_phone: 290192019,
  company_address1: 'JL. Test company No.01',
  company_address2: 'Kec. Sawangan Bangau',
  company_city: 'Jakarta Barat',
  company_state: 'DKI Jakarta',
  company_zip_code: '37862',
  company_country: 'Indonesia',
  company_vat: 'aw',
  company_website: 'test.id',
  company_bank_name: 'BCA',
  company_bank_account: '03920192910',
}
export const invalidCompanyName = {
  uuid: 'xyz',
  company_name: '',
  company_contact: 'Inggil',
  company_email: 'test@paper.id',
  company_phone: 290192019,
  company_address1: 'JL. Test company No.01',
  company_address2: 'Kec. Sawangan Bangau',
  company_city: 'Jakarta Barat',
  company_state: 'DKI Jakarta',
  company_zip_code: '37862',
  company_country: 'Indonesia',
  company_vat: 'aw',
  company_website: 'test.id',
  company_bank_name: 'BCA',
  company_bank_account: '03920192910',
}
export const invalidEmail = {
  uuid: 'xyz',
  company_name: 'Company Test',
  company_contact: 'Inggil',
  company_email: '',
  company_phone: 3213121211,
  company_address1: 'JL. Test company No.01',
  company_address2: 'Kec. Sawangan Bangau',
  company_city: 'Jakarta Barat',
  company_state: 'DKI Jakarta',
  company_zip_code: '37862',
  company_country: 'Indonesia',
  company_vat: 'aw',
  company_website: 'test.id',
  company_bank_name: 'BCA',
  company_bank_account: '03920192910',
}
export const invalidPhone = {
  uuid: 'xyz',
  company_name: 'Company Test',
  company_contact: 'Inggil',
  company_email: 'test@paper.id',
  company_phone: '',
  company_address1: 'JL. Test company No.01',
  company_address2: 'Kec. Sawangan Bangau',
  company_city: 'Jakarta Barat',
  company_state: 'DKI Jakarta',
  company_zip_code: '37862',
  company_country: 'Indonesia',
  company_vat: 'aw',
  company_website: 'test.id',
  company_bank_name: 'BCA',
  company_bank_account: '03920192910',
}
export const invalidAdrressOne = {
  uuid: 'xyz',
  company_name: 'Company Test',
  company_contact: 'Inggil',
  company_email: 'test@paper.id',
  company_phone: 290192019,
  company_address1: '',
  company_address2: 'Kec. Sawangan Bangau',
  company_city: 'Jakarta Barat',
  company_state: 'DKI Jakarta',
  company_zip_code: '37862',
  company_country: 'Indonesia',
  company_vat: 'aw',
  company_website: 'test.id',
  company_bank_name: 'BCA',
  company_bank_account: '03920192910',
}
export const invalidCity = {
  uuid: 'xyz',
  company_name: 'Company Test',
  company_contact: 'Inggil',
  company_email: 'test@paper.id',
  company_phone: 290192019,
  company_address1: 'JL. Test company No.01',
  company_address2: 'Kec. Sawangan Bangau',
  company_city: '',
  company_state: 'DKI Jakarta',
  company_zip_code: '37862',
  company_country: 'Indonesia',
  company_vat: 'aw',
  company_website: 'test.id',
  company_bank_name: 'BCA',
  company_bank_account: '03920192910',
}
export const invalidState = {
  uuid: 'xyz',
  company_name: 'Company Test',
  company_contact: 'Inggil',
  company_email: 'test@paper.id',
  company_phone: 290192019,
  company_address1: 'JL. Test company No.01',
  company_address2: 'Kec. Sawangan Bangau',
  company_city: 'Jakarta Barat',
  company_state: '',
  company_zip_code: '37862',
  company_country: 'Indonesia',
  company_vat: 'aw',
  company_website: 'test.id',
  company_bank_name: 'BCA',
  company_bank_account: '03920192910',
}
export const invalidCountry = {
  uuid: 'xyz',
  company_name: 'Company Test',
  company_contact: 'Inggil',
  company_email: 'test@paper.id',
  company_phone: 290192019,
  company_address1: 'JL. Test company No.01',
  company_address2: 'Kec. Sawangan Bangau',
  company_city: 'Jakarta Barat',
  company_state: 'DKI Jakarta',
  company_zip_code: '37862',
  company_country: '',
  company_vat: 'aw',
  company_website: 'test.id',
  company_bank_name: 'BCA',
  company_bank_account: '03920192910',
}